version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql@16/data
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dbconversor
  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes: 
      - cache:/data
  
  apache:
    image: httpd:latest
    container_name: carpetasApache
    ports:
    - '8080:80'
    volumes:
    - ../archivos:/usr/local/apache2/htdocs
volumes:
  cache:
    driver: local